Added Slovenian translations
WebChemistry/invoice pull request #10
Opened 2019-04-14 08:08 UTC by valjar

2019-04-14 10:16 UTC, MartkCz commented on src/Formatter.php
> +        'si' => [
Please, use tabs instead of spaces

2019-04-14 10:16 UTC, MartkCz commented on src/Translator.php
> +        SLOVENIAN = 'si';
Please, use tabs instead of spaces

2019-04-14 10:16 UTC, MartkCz commented on src/Translator.php
> +        'si' => [
Please, use tabs instead of spaces

2019-11-12 12:52 UTC, adaamz requested changes
use tabs everywhere, not only on those 3 mentioned places

2019-11-12 12:53 UTC, closed without merging